"""Add total_tries and highest_level_completed to User, create UserLevelStats.

Revision ID: 3edd3c605f31
Revises: 268bb438c1db
Create Date: 2024-11-27 08:47:44.049431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edd3c605f31'
down_revision = '268bb438c1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_level_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.String(length=50), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('highest_level_completed', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('highest_level_completed')
        batch_op.drop_column('total_tries')

    op.drop_table('user_level_stats')
    # ### end Alembic commands ###
