"""Add completion_date fields.

Revision ID: d8f6e3c91caf
Revises: 3edd3c605f31
Create Date: 2024-11-30 17:13:21.582016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f6e3c91caf'
down_revision = '3edd3c605f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_level_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_level_completed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('highest_level_completed_date')

    with op.batch_alter_table('user_level_stats', schema=None) as batch_op:
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###
